# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'adocaoAnimal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Adoção Animal
  pod 'Firebase/Core'
  pod "ESTabBarController-swift"
  pod 'GoogleSignIn'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftUtilities'
  pod 'RxSwiftExt'

  # Rx Firebase utilities
  pod 'RxFirebase/Firestore'
  pod 'RxFirebase/RemoteConfig'
  pod 'RxFirebase/Database'
  pod 'RxFirebase/Storage'
  pod 'RxFirebase/Auth'
  pod 'RxFirebase/Functions'

  pod 'lottie-ios'     #Animations
  pod 'R.swift'

  pod 'TPKeyboardAvoiding', '~> 1.3'

  target 'adocaoAnimalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'adocaoAnimalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
