# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'adocaoAnimal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Adoção Animal
  pod 'Firebase/Core'
  pod "ESTabBarController-swift"
  pod 'ChatSDK'
  pod 'ChatSDKFirebase/Adapter'
  pod 'ChatSDKFirebase/FileStorage'
  pod 'ChatSDKFirebase/Push'
  pod 'ChatSDKFirebase/SocialLogin'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxSwiftUtilities'
  pod 'RxSwiftExt'
  pod 'lottie-ios'     #Animations
  pod 'R.swift'

  target 'adocaoAnimalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'adocaoAnimalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
